n_classes: 9
transformations:
  patch_size: [512, 640]
  scaling: true
  rotation: true
  gaussian_noise: true
  gaussian_blur: true
  low_resolution: false
  brightness: true
  contrast: true
  gamma: true
  mirror: true
  dummy_2d: false
oversample_ratio: 0.33
batch_size: 64
num_workers: 14
infer_batch_size: 6
infer_num_workers: 4
sw_batch_size: 24
sw_overlap: 0.5
n_epochs: 100
val_plot_interval: 2
grad_clip_max_norm: 12
grad_accumulate_step: 4
lr_scheduler:
  name: PolynomialLR
  total_iters: 100
  power: 0.9
optimizer:
  name: AdamW
  lr: 0.0001
model:
  arch: UnetPlusPlus
  encoder_name: tu-mobilenetv3_small_100
  encoder_weights: imagenet
  in_channels: 3
  classes: 10
dataset_path: /content/STSeg_train_10
